language: node_js
node_js:
  - "8"
  - "6"
  - "4"
  - "10"
services:
  - postgresql
env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres

install:
  - npm install -g node-gyp
  - npm install

script:
  - gulp lint
  - gulp build
  - gulp test

sudo: false
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
